<?php
require_once 'inc/option.php';
if (empty($_SESSION['logged'])) { header('Location: ' . app_url('login')); exit; }
require_permission('manage_teams');
$app = new SmsApp();
$message = '';
$openModal = false;
if ($_SERVER['REQUEST_METHOD'] === 'POST' && !empty($_POST['action'])) {
    if (!verify_csrf_token($_POST['csrf_token'] ?? '')) { $message = 'Token di sicurezza non valido.'; }
    elseif ($_POST['action'] === 'save_team') {
        $saved = $app->saveTeam($_POST); $message = $saved ? 'Team salvato.' : 'Impossibile salvare il team.'; $openModal = !$saved;
        system_log($saved ? 'info' : 'error', 'team', $saved ? 'team.saved' : 'team.save_failed', $message, ['company_id' => (int)($_POST['company_id'] ?? current_company_id()), 'team_id' => (int)($_POST['id'] ?? 0), 'team_name' => trim((string)($_POST['name'] ?? ''))]);
    } elseif ($_POST['action'] === 'delete_team') {
        $team = $app->getTeamById((int)($_POST['id'] ?? 0)); $deleted = $app->deleteTeam((int)($_POST['id'] ?? 0)); $message = $deleted ? 'Team eliminato.' : 'Impossibile eliminare il team: riassegna prima gli utenti.';
        system_log($deleted ? 'info' : 'warning', 'team', $deleted ? 'team.deleted' : 'team.delete_failed', $message, ['company_id' => (int)($team['company_id'] ?? current_company_id()), 'team_id' => (int)($_POST['id'] ?? 0), 'team_name' => (string)($team['name'] ?? '')]);
    }
}
$filters = ['search' => trim((string)($_GET['search'] ?? '')), 'active' => (string)($_GET['active'] ?? 'all'), 'company_id' => (int)($_GET['company_id'] ?? 0)];
$teams = $app->getTeams($filters); $companies = $app->getCompanies(true); $editingTeam = !empty($_GET['edit']) ? $app->getTeamById((int)$_GET['edit']) : null; if ($editingTeam) $openModal = true;
$submitted = $_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'save_team'; $flashMessage = flash_message();
?>
<!DOCTYPE html><html lang="it"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Gestione team</title><link rel="icon" href="imgs/favicon.ico?v=2" sizes="any"><link rel="icon" type="image/png" sizes="32x32" href="imgs/favicon-32.png?v=2"><link rel="apple-touch-icon" href="imgs/favicon-180.png?v=2"><link rel="stylesheet" href="css/style.css"><link rel="stylesheet" href="css/loggedstyle.css"></head>
<body class="page-teams"><div id="wrapper" class="dashboard-shell"><div id="header"><div><p class="eyebrow">Organizzazione</p><h2>Gestione team</h2></div><div class="header-actions"><span class="user-badge"><?php echo htmlspecialchars($_SESSION['logged'], ENT_QUOTES, 'UTF-8'); ?></span><a href="<?php echo app_url('logout'); ?>" class="logout-link">Logout</a></div></div>
<?php require 'inc/top_nav.php'; ?>
<?php if($flashMessage!==''):?><div class="alert alert-danger"><?php echo htmlspecialchars($flashMessage,ENT_QUOTES,'UTF-8');?></div><?php endif;?><?php if($message!==''):?><div class="alert"><?php echo htmlspecialchars($message,ENT_QUOTES,'UTF-8');?></div><?php endif;?>
<section class="page-heading"><div><p class="eyebrow">Struttura aziendale</p><h1>Team</h1><p class="muted-text">Organizza utenti e amministratori nei team della stessa azienda.</p></div><span class="heading-pill"><?php echo htmlspecialchars(is_super_admin() ? 'Vista globale' : (string)($_SESSION['company_name'] ?? 'Azienda'),ENT_QUOTES,'UTF-8');?></span></section>
<section class="card"><div class="section-heading"><div><p class="eyebrow">Organigramma</p><h3>Team configurati</h3></div><button type="button" class="modal-trigger-btn" id="openTeamModal">Nuovo team</button></div>
<form method="get" class="filter-bar"><input type="hidden" name="route" value="teams"><input name="search" value="<?php echo htmlspecialchars($filters['search'],ENT_QUOTES,'UTF-8');?>" placeholder="Cerca team o azienda"><?php if(is_super_admin()):?><select name="company_id"><option value="0">Tutte le aziende</option><?php foreach($companies as $company):?><option value="<?php echo (int)$company['id'];?>" <?php echo $filters['company_id']===(int)$company['id']?'selected':'';?>><?php echo htmlspecialchars((string)$company['name'],ENT_QUOTES,'UTF-8');?></option><?php endforeach;?></select><?php endif;?><select name="active"><option value="all">Tutti</option><option value="1" <?php echo $filters['active']==='1'?'selected':'';?>>Attivi</option><option value="0" <?php echo $filters['active']==='0'?'selected':'';?>>Disattivi</option></select><input type="submit" value="Filtra"></form>
<div class="table-wrap"><table class="data-table"><thead><tr><th>Team</th><th>Azienda</th><th>Utenti</th><th>Stato</th><th>Creato</th><th>Azioni</th></tr></thead><tbody><?php if(empty($teams)):?><tr><td colspan="6">Nessun team trovato.</td></tr><?php endif;?><?php foreach($teams as $team):?><tr><td><?php echo htmlspecialchars((string)$team['name'],ENT_QUOTES,'UTF-8');?></td><td><?php echo htmlspecialchars((string)$team['company_name'],ENT_QUOTES,'UTF-8');?></td><td><?php echo (int)$team['user_count'];?></td><td><span class="status-pill <?php echo (int)$team['active']===1?'sent':'failed';?>"><?php echo (int)$team['active']===1?'Attivo':'Disattivo';?></span></td><td><?php echo htmlspecialchars((string)$team['created_at'],ENT_QUOTES,'UTF-8');?></td><td class="actions-cell"><a class="action-btn" href="<?php echo app_url('teams',['edit'=>(int)$team['id']]);?>">Modifica</a><form method="post" onsubmit="return confirm('Eliminare questo team?');"><?php echo csrf_field();?><input type="hidden" name="action" value="delete_team"><input type="hidden" name="id" value="<?php echo (int)$team['id'];?>"><button class="action-btn danger-btn" type="submit">Elimina</button></form></td></tr><?php endforeach;?></tbody></table></div></section></div>
<div class="modal-overlay <?php echo $openModal?'is-active':'';?>" id="teamModal"><div class="modal-card"><div class="modal-header"><div><p class="eyebrow"><?php echo $editingTeam?'Modifica':'Nuovo';?></p><h3><?php echo $editingTeam?'Aggiorna team':'Crea team';?></h3></div><button type="button" class="modal-close-btn" id="closeTeamModal" aria-label="Chiudi popup">x</button></div><form method="post" class="stacked-form"><input type="hidden" name="action" value="save_team"><?php echo csrf_field();?><input type="hidden" name="id" value="<?php echo (int)($editingTeam['id']??0);?>"><?php if(is_super_admin()):?><label for="company_id">Azienda</label><select id="company_id" name="company_id" required><option value="">Seleziona azienda</option><?php $selectedCompany=(int)($_POST['company_id']??($editingTeam['company_id']??0));foreach($companies as $company):?><option value="<?php echo (int)$company['id'];?>" <?php echo $selectedCompany===(int)$company['id']?'selected':'';?>><?php echo htmlspecialchars((string)$company['name'],ENT_QUOTES,'UTF-8');?></option><?php endforeach;?></select><?php endif;?><label for="name">Nome team</label><input id="name" name="name" required value="<?php echo htmlspecialchars((string)($_POST['name']??($editingTeam['name']??'')),ENT_QUOTES,'UTF-8');?>"><div class="checkbox-row"><label><input type="checkbox" name="active" value="1" <?php echo $submitted?(!empty($_POST['active'])?'checked':''):(!isset($editingTeam['active'])||(int)$editingTeam['active']===1?'checked':'');?>> Team attivo</label></div><div class="form-actions"><input type="submit" value="Salva team"></div></form></div></div>
<script>(function(){var m=document.getElementById('teamModal'),o=document.getElementById('openTeamModal'),c=document.getElementById('closeTeamModal'),u=<?php echo json_encode(app_url('teams')); ?>;if(!m||!o||!c)return;o.addEventListener('click',function(){m.classList.add('is-active');});function close(){window.location.href=u;}c.addEventListener('click',close);m.addEventListener('click',function(e){if(e.target===m)close();});}());</script></body></html>
